### ISSUE TITLE
Discussion: Citation and licensing considerations

### ISSUE THREAD

**Issue by timrobertson100** [plantnet/gbif-dl#51]
Thank you very much for sharing this utility. 

We're heading into relatively new territory for the GBIF community where images will increasingly be used in ML to build models. It's currently unclear how publishers will feel about this when learning that their photos are used in this way. Even if it could be argued that copyright isn't being infringed upon since photos are not being redistributed (the equivalent of "not infringing copyright by creating an index allowing you to find Shakespeare works containing _Romeo_") it may result in images being withheld in the future.

I suggest it would be wise to firstly acknowledge this situation in the README and presentations. Secondly, it would be good to promote a citation practice that acknowledges the sources of training data - e.g. the built models are given a DOI that links (cites) the source dataset DOIs. Thirdly, it might be prudent to restrict this to only CC0 and CC-BY licensed images.

At GBIF we are interested to see open discussion around these aspects.

Thanks!

**Comment by timrobertson100** [comment]
As an example, please see https://doi.org/10.26161/mpbc-q144 which illustrates how we use a DOI-based citation for the model in TensorFlow Hub, where [the DOI metadata](https://api.datacite.org/dois/10.26161/mpbc-q144) links using the `IsDerivedFrom` relationship to the training dataset https://doi.org/10.15468/zn159h.

**Comment by faroit** [comment]
HI @timrobertson100 these are very import issues, thanks for raising them here. My plan was to also head over to gbifs discourse channels to bring this up over there when this tool would be out of alpha stage. 

> I suggest it would be wise to firstly acknowledge this situation in the README and presentations. 

Yes, that sounds good. do you have some excerpt in mind that would be clear enough?

> Secondly, it would be good to promote a citation practice that acknowledges the sources of training data - e.g. the built models are given a DOI that links (cites) the source dataset DOIs. 

I will have a look what would be the best way to do that. For now, maybe I can aggregate the dois for each retrieved sample from its original dataset and offer this to the user through this tool. For the next steps we are looking for a way to make the datasets more reproducible thus allowing users to reupload media data to stores such as zenodo. So this would be a very important aspect to it. 

> Thirdly, it might be prudent to restrict this to only CC0 and CC-BY licensed images.

That sounds good to me, yes. Would you say that this would be just the default that could be overridden manually?

**Comment by timrobertson100** [comment]
Thanks, @faroit - I think it would be an excellent step to open this on the GBIF Discourse for discussion

I don't have an excerpt but perhaps you could open the discussion on Discourse and simply acknowledge the concern in the readme, and link to the discussion showing that you are actively seeking guidance on how to best work with the community of publishers?

> Would you say that this would be just the default that could be overridden manually?

Makes sense. It makes it easy for people to do the right (or "conservative") thing.  Thanks

**Comment by alexisjoly** [comment]
We added the following disclaimer to the README:
## Disclaimer
Unlike GBIF occurrences that all have a creative common license (CC0, CC BY, or CC BY-NC), GBIF does not give any official recommendation for licensing shared media files. The License fields are essentially free text filled in by the data provider. Data providers are strongly encouraged to set their licenses in a machine-readable format, but there is no guarantee. Thus, it is the responsibility of GBIF-DL users to set up the appropriate filters on the license field and to respect the conditions of use of these licenses.

**Comment by alexisjoly** [comment]
Completed the disclaimer with: Since we are heading into relatively new territory regarding the use of GBIF media files for machine learning, it is currently unclear how publishers will feel about this when learning that their photos are used in this way. At Pl@ntNet, the choice to publish our images in GBIF has been carefully considered and we are fully aware that they would probably be used for this purpose. But we fully understand that some other data providers didn't think of this and we are interested to have open discussion around these aspects.

**Comment by timrobertson100** [comment]
Thanks, @faroit and @alexisjoly for accommodating this. 

You might be interested to see the creative commons folk start to [discuss this topic too](https://creativecommons.org/2021/03/04/should-cc-licensed-content-be-used-to-train-ai-it-depends/).

I think this issue can be closed, and reopened if new info comes up.
