### ISSUE TITLE
AttributeError: module 'pygbif' has no attribute 'occurrences'

### ISSUE THREAD

**Issue by dmuralik** [plantnet/gbif-dl#68]
When trying to download, i get this error. 
Code:
`import gbif_dl
data_generator = gbif_dl.api.generate_urls(
    queries=query_per_species,
    label="speciesKey",
    nb_samples=100,
    weighted_streams=True
)
stats = gbif_dl.io.download(data_generator, root="/content/gdrive/MyDrive/efc-images/plantnet")
`

Error:
0 Files [00:00, ? Files/s]Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/gbif_dl/utils.py", line 44, in run
    self.result = runners.run(self.func(*self.args, **self.kwargs))
  File "/usr/local/lib/python3.7/dist-packages/gbif_dl/runners.py", line 104, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/gbif_dl/io.py", line 242, in _download_from_asyncgen
    async for batch in chnk:
  File "/usr/local/lib/python3.7/dist-packages/aiostream/stream/transform.py", line 87, in chunks
    async for first in streamer:
  File "/usr/local/lib/python3.7/dist-packages/aiostream/stream/create.py", line 34, in from_iterable
    for item in it:
  File "/usr/local/lib/python3.7/dist-packages/pescador/core.py", line 204, in iterate
    for n, obj in enumerate(active_streamer.stream_):
  File "/usr/local/lib/python3.7/dist-packages/gbif_dl/generators/api.py", line 43, in gbif_query_generator
    resp = pygbif.occurrences.search(
AttributeError: module 'pygbif' has no attribute 'occurrences'

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-40-8dcc5b34b6dc> in <module>()
----> 1 stats = gbif_dl.io.download(data_generator, root="/content/gdrive/MyDrive/efc-images/plantnet")
      2 print(stats)

1 frames

/usr/local/lib/python3.7/dist-packages/gbif_dl/io.py in download(items, root, tcp_connections, nb_workers, batch_size, retries, verbose, overwrite, is_valid_file, proxy, random_subsets)
    316         is_valid_file=is_valid_file,
    317         proxy=proxy,
--> 318         random_subsets=random_subsets,
    319     )

/usr/local/lib/python3.7/dist-packages/gbif_dl/utils.py in run_async(func, *args, **kwargs)
     58         thread.start()
     59         thread.join()
---> 60         return thread.result
     61     else:
     62         return runners.run(func(*args, **kwargs))

AttributeError: 'RunThread' object has no attribute 'result'

**Comment by faroit** [comment]
@dmuralik thats weird. I which version of pygbif did you install?

**Comment by dmuralik** [comment]
@faroit  When i did pip install gbif-dl , it looks like it installed pygbif-0.6.0 and i havent tried changing the version of pygbif-0.6.0 yet which i could

**Comment by faroit** [comment]
> @faroit  When i did pip install gbif-dl , it looks like it installed pygbif-0.6.0 and i havent tried changing the version of pygbif-0.6.0 yet which i could

Thanks. I will check this in the next days. Maybe 0.6.0 introduced some breaking changes.

**Comment by dmuralik** [comment]
@faroit When i just tried using gbif-dl as-is with pygbif-0.6.0, i didnt get that error again. So, i am not sure what could have caused it. I am using google colab, so i am going to have to blame it on the runtime or the host setup that somehow something got messed up. I am going to be dabbling with this a little bit before I close it. Thanks for your response anyway.
